name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
       host: convert-docs.opengeospatial.org
       username: greg
       key: ${{ secrets.KEY }}
       port: 7822
       script: |
         cd /web/convert-docs/test/
         git clone https://github.com/ogctest/GeoPoseWeb.git
